version: "3"
services:
  app:
    image: node-app-image
    container_name: node-app
    build: .
    ports:
      - "3000:3001"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    environment:
      - PORT=3001
    env_file:
      - ./.env