version: "3"
services:
  app:
    image: node-app-image
    container_name: node-app
    restart: always
    build: .
    ports:
      - "3000:3001"
    volumes:
      - ./dist:/app/dist
    environment:
      - PORT=3001
      - HELLO=world
    env_file:
      # 如果变量同名，下一个会覆盖上一个
      - ./.env
      - ./.env.testing
      - ./.env.development
      - ./.env.production
    depends_on:
      - redis
      - mysql
    networks:
      - network
##############################
# 用了 docker 的 network 后， node-app 容器就能用「内网」连接 node-mysql:3366, node-redis:6380
##############################
  mysql:
    image: mysql/mysql-server:8.0.27
    container_name: node-mysql
    restart: always
    ports:
      - "3366:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - network
###############################
  redis:
    image: redis:5-alpine
    container_name: node-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis:/data
    networks:
      - network
###############################
volumes:
  mysql:
  redis:
###############################
networks:
  network:
